var annotated_dup =
[
    [ "Signals", "namespace_signals.html", [
      [ "Common", "namespace_signals_1_1_common.html", [
        [ "BoolSignal", "class_signals_1_1_common_1_1_bool_signal.html", null ],
        [ "BoolSignalEditor", "class_signals_1_1_common_1_1_bool_signal_editor.html", "class_signals_1_1_common_1_1_bool_signal_editor" ],
        [ "BoolSignalListener", "class_signals_1_1_common_1_1_bool_signal_listener.html", null ],
        [ "BoolValueReferenceDrawer", "class_signals_1_1_common_1_1_bool_value_reference_drawer.html", null ],
        [ "CharSignal", "class_signals_1_1_common_1_1_char_signal.html", null ],
        [ "CharSignalEditor", "class_signals_1_1_common_1_1_char_signal_editor.html", "class_signals_1_1_common_1_1_char_signal_editor" ],
        [ "CharSignalListener", "class_signals_1_1_common_1_1_char_signal_listener.html", null ],
        [ "CharValueReferenceDrawer", "class_signals_1_1_common_1_1_char_value_reference_drawer.html", null ],
        [ "FloatSignal", "class_signals_1_1_common_1_1_float_signal.html", null ],
        [ "FloatSignalEditor", "class_signals_1_1_common_1_1_float_signal_editor.html", "class_signals_1_1_common_1_1_float_signal_editor" ],
        [ "FloatSignalListener", "class_signals_1_1_common_1_1_float_signal_listener.html", null ],
        [ "FloatValueReferenceDrawer", "class_signals_1_1_common_1_1_float_value_reference_drawer.html", null ],
        [ "IntSignal", "class_signals_1_1_common_1_1_int_signal.html", null ],
        [ "IntSignalEditor", "class_signals_1_1_common_1_1_int_signal_editor.html", "class_signals_1_1_common_1_1_int_signal_editor" ],
        [ "IntSignalListener", "class_signals_1_1_common_1_1_int_signal_listener.html", null ],
        [ "IntValueReferenceDrawer", "class_signals_1_1_common_1_1_int_value_reference_drawer.html", null ],
        [ "QuaternionSignal", "class_signals_1_1_common_1_1_quaternion_signal.html", null ],
        [ "QuaternionSignalEditor", "class_signals_1_1_common_1_1_quaternion_signal_editor.html", "class_signals_1_1_common_1_1_quaternion_signal_editor" ],
        [ "QuaternionSignalListener", "class_signals_1_1_common_1_1_quaternion_signal_listener.html", null ],
        [ "QuaternionValueReferenceDrawer", "class_signals_1_1_common_1_1_quaternion_value_reference_drawer.html", "class_signals_1_1_common_1_1_quaternion_value_reference_drawer" ],
        [ "StringSignal", "class_signals_1_1_common_1_1_string_signal.html", null ],
        [ "StringSignalEditor", "class_signals_1_1_common_1_1_string_signal_editor.html", "class_signals_1_1_common_1_1_string_signal_editor" ],
        [ "StringSignalListener", "class_signals_1_1_common_1_1_string_signal_listener.html", null ],
        [ "StringValueReferenceDrawer", "class_signals_1_1_common_1_1_string_value_reference_drawer.html", null ],
        [ "Vector2IntSignal", "class_signals_1_1_common_1_1_vector2_int_signal.html", null ],
        [ "Vector2IntSignalEditor", "class_signals_1_1_common_1_1_vector2_int_signal_editor.html", "class_signals_1_1_common_1_1_vector2_int_signal_editor" ],
        [ "Vector2IntSignalListener", "class_signals_1_1_common_1_1_vector2_int_signal_listener.html", null ],
        [ "Vector2IntValueReferenceDrawer", "class_signals_1_1_common_1_1_vector2_int_value_reference_drawer.html", null ],
        [ "Vector2Signal", "class_signals_1_1_common_1_1_vector2_signal.html", null ],
        [ "Vector2SignalEditor", "class_signals_1_1_common_1_1_vector2_signal_editor.html", "class_signals_1_1_common_1_1_vector2_signal_editor" ],
        [ "Vector2SignalListener", "class_signals_1_1_common_1_1_vector2_signal_listener.html", null ],
        [ "Vector2ValueReferenceDrawer", "class_signals_1_1_common_1_1_vector2_value_reference_drawer.html", null ],
        [ "Vector3IntSignal", "class_signals_1_1_common_1_1_vector3_int_signal.html", null ],
        [ "Vector3IntSignalEditor", "class_signals_1_1_common_1_1_vector3_int_signal_editor.html", "class_signals_1_1_common_1_1_vector3_int_signal_editor" ],
        [ "Vector3IntSignalListener", "class_signals_1_1_common_1_1_vector3_int_signal_listener.html", null ],
        [ "Vector3IntValueReferenceDrawer", "class_signals_1_1_common_1_1_vector3_int_value_reference_drawer.html", null ],
        [ "Vector3Signal", "class_signals_1_1_common_1_1_vector3_signal.html", null ],
        [ "Vector3SignalEditor", "class_signals_1_1_common_1_1_vector3_signal_editor.html", "class_signals_1_1_common_1_1_vector3_signal_editor" ],
        [ "Vector3SignalListener", "class_signals_1_1_common_1_1_vector3_signal_listener.html", null ],
        [ "Vector3ValueReferenceDrawer", "class_signals_1_1_common_1_1_vector3_value_reference_drawer.html", null ],
        [ "Vector4Signal", "class_signals_1_1_common_1_1_vector4_signal.html", null ],
        [ "Vector4SignalEditor", "class_signals_1_1_common_1_1_vector4_signal_editor.html", "class_signals_1_1_common_1_1_vector4_signal_editor" ],
        [ "Vector4SignalListener", "class_signals_1_1_common_1_1_vector4_signal_listener.html", null ],
        [ "Vector4ValueReferenceDrawer", "class_signals_1_1_common_1_1_vector4_value_reference_drawer.html", "class_signals_1_1_common_1_1_vector4_value_reference_drawer" ]
      ] ],
      [ "Examples", "namespace_signals_1_1_examples.html", [
        [ "ExamplePlayerCharacterInput", "class_signals_1_1_examples_1_1_example_player_character_input.html", "class_signals_1_1_examples_1_1_example_player_character_input" ],
        [ "FallingCube", "class_signals_1_1_examples_1_1_falling_cube.html", "class_signals_1_1_examples_1_1_falling_cube" ],
        [ "GravityYSignalUpdater", "class_signals_1_1_examples_1_1_gravity_y_signal_updater.html", "class_signals_1_1_examples_1_1_gravity_y_signal_updater" ],
        [ "Logger", "class_signals_1_1_examples_1_1_logger.html", "class_signals_1_1_examples_1_1_logger" ],
        [ "Name", "class_signals_1_1_examples_1_1_name.html", null ],
        [ "TextSetter", "class_signals_1_1_examples_1_1_text_setter.html", "class_signals_1_1_examples_1_1_text_setter" ],
        [ "TimeScaleSignalUpdater", "class_signals_1_1_examples_1_1_time_scale_signal_updater.html", "class_signals_1_1_examples_1_1_time_scale_signal_updater" ]
      ] ],
      [ "Extras", "namespace_signals_1_1_extras.html", [
        [ "Characters", "namespace_signals_1_1_extras_1_1_characters.html", [
          [ "CharacterMoveSignal", "class_signals_1_1_extras_1_1_characters_1_1_character_move_signal.html", "class_signals_1_1_extras_1_1_characters_1_1_character_move_signal" ],
          [ "PlayerCharacterInput", "class_signals_1_1_extras_1_1_characters_1_1_player_character_input.html", "class_signals_1_1_extras_1_1_characters_1_1_player_character_input" ],
          [ "PlayerCharacterInputSettings", "class_signals_1_1_extras_1_1_characters_1_1_player_character_input_settings.html", "class_signals_1_1_extras_1_1_characters_1_1_player_character_input_settings" ],
          [ "PlayerCharacterInputSettingsSignal", "class_signals_1_1_extras_1_1_characters_1_1_player_character_input_settings_signal.html", null ],
          [ "PlayerCharacterInputSettingsSignalEditor", "class_signals_1_1_extras_1_1_characters_1_1_player_character_input_settings_signal_editor.html", null ],
          [ "RigidbodyCharacter", "class_signals_1_1_extras_1_1_characters_1_1_rigidbody_character.html", "class_signals_1_1_extras_1_1_characters_1_1_rigidbody_character" ],
          [ "RigidbodyCharacterSettings", "class_signals_1_1_extras_1_1_characters_1_1_rigidbody_character_settings.html", "class_signals_1_1_extras_1_1_characters_1_1_rigidbody_character_settings" ],
          [ "RigidbodyCharacterSettingsSignal", "class_signals_1_1_extras_1_1_characters_1_1_rigidbody_character_settings_signal.html", null ],
          [ "RigidbodyCharacterSettingsSignalEditor", "class_signals_1_1_extras_1_1_characters_1_1_rigidbody_character_settings_signal_editor.html", null ],
          [ "TopDownPlayerCharacterInput", "class_signals_1_1_extras_1_1_characters_1_1_top_down_player_character_input.html", "class_signals_1_1_extras_1_1_characters_1_1_top_down_player_character_input" ]
        ] ],
        [ "Engine", "namespace_signals_1_1_extras_1_1_engine.html", [
          [ "ApplicationSettings", "class_signals_1_1_extras_1_1_engine_1_1_application_settings.html", "class_signals_1_1_extras_1_1_engine_1_1_application_settings" ],
          [ "ApplicationSettingsSignal", "class_signals_1_1_extras_1_1_engine_1_1_application_settings_signal.html", null ],
          [ "ApplicationSettingsSignalEditor", "class_signals_1_1_extras_1_1_engine_1_1_application_settings_signal_editor.html", null ],
          [ "ApplicationSetup", "class_signals_1_1_extras_1_1_engine_1_1_application_setup.html", null ],
          [ "ApplicationSetupEditor", "class_signals_1_1_extras_1_1_engine_1_1_application_setup_editor.html", null ],
          [ "ApplicationWrapper", "class_signals_1_1_extras_1_1_engine_1_1_application_wrapper.html", "class_signals_1_1_extras_1_1_engine_1_1_application_wrapper" ],
          [ "ApplicationWrapperEditor", "class_signals_1_1_extras_1_1_engine_1_1_application_wrapper_editor.html", "class_signals_1_1_extras_1_1_engine_1_1_application_wrapper_editor" ],
          [ "DebugWrapper", "class_signals_1_1_extras_1_1_engine_1_1_debug_wrapper.html", "class_signals_1_1_extras_1_1_engine_1_1_debug_wrapper" ],
          [ "EngineSettingsSignal", "class_signals_1_1_extras_1_1_engine_1_1_engine_settings_signal.html", "class_signals_1_1_extras_1_1_engine_1_1_engine_settings_signal" ],
          [ "EngineSettingsSignalEditor", "class_signals_1_1_extras_1_1_engine_1_1_engine_settings_signal_editor.html", "class_signals_1_1_extras_1_1_engine_1_1_engine_settings_signal_editor" ],
          [ "EngineSetup", "class_signals_1_1_extras_1_1_engine_1_1_engine_setup.html", "class_signals_1_1_extras_1_1_engine_1_1_engine_setup" ],
          [ "EngineSetupEditor", "class_signals_1_1_extras_1_1_engine_1_1_engine_setup_editor.html", "class_signals_1_1_extras_1_1_engine_1_1_engine_setup_editor" ],
          [ "EngineWrapperEditor", "class_signals_1_1_extras_1_1_engine_1_1_engine_wrapper_editor.html", "class_signals_1_1_extras_1_1_engine_1_1_engine_wrapper_editor" ],
          [ "IEngineSettings", "interface_signals_1_1_extras_1_1_engine_1_1_i_engine_settings.html", "interface_signals_1_1_extras_1_1_engine_1_1_i_engine_settings" ],
          [ "PhysicsSettings", "class_signals_1_1_extras_1_1_engine_1_1_physics_settings.html", "class_signals_1_1_extras_1_1_engine_1_1_physics_settings" ],
          [ "PhysicsSettingsSignal", "class_signals_1_1_extras_1_1_engine_1_1_physics_settings_signal.html", null ],
          [ "PhysicsSettingsSignalEditor", "class_signals_1_1_extras_1_1_engine_1_1_physics_settings_signal_editor.html", null ],
          [ "PhysicsSetup", "class_signals_1_1_extras_1_1_engine_1_1_physics_setup.html", null ],
          [ "PhysicsSetupEditor", "class_signals_1_1_extras_1_1_engine_1_1_physics_setup_editor.html", null ],
          [ "PhysicsWrapper", "class_signals_1_1_extras_1_1_engine_1_1_physics_wrapper.html", "class_signals_1_1_extras_1_1_engine_1_1_physics_wrapper" ],
          [ "PhysicsWrapperEditor", "class_signals_1_1_extras_1_1_engine_1_1_physics_wrapper_editor.html", "class_signals_1_1_extras_1_1_engine_1_1_physics_wrapper_editor" ],
          [ "TimeSettings", "class_signals_1_1_extras_1_1_engine_1_1_time_settings.html", "class_signals_1_1_extras_1_1_engine_1_1_time_settings" ],
          [ "TimeSettingsSignal", "class_signals_1_1_extras_1_1_engine_1_1_time_settings_signal.html", null ],
          [ "TimeSettingsSignalEditor", "class_signals_1_1_extras_1_1_engine_1_1_time_settings_signal_editor.html", null ],
          [ "TimeSetup", "class_signals_1_1_extras_1_1_engine_1_1_time_setup.html", null ],
          [ "TimeSetupEditor", "class_signals_1_1_extras_1_1_engine_1_1_time_setup_editor.html", null ],
          [ "TimeWrapper", "class_signals_1_1_extras_1_1_engine_1_1_time_wrapper.html", "class_signals_1_1_extras_1_1_engine_1_1_time_wrapper" ],
          [ "TimeWrapperEditor", "class_signals_1_1_extras_1_1_engine_1_1_time_wrapper_editor.html", "class_signals_1_1_extras_1_1_engine_1_1_time_wrapper_editor" ]
        ] ],
        [ "Utility", "namespace_signals_1_1_extras_1_1_utility.html", [
          [ "EulerAnglesTracker", "class_signals_1_1_extras_1_1_utility_1_1_euler_angles_tracker.html", "class_signals_1_1_extras_1_1_utility_1_1_euler_angles_tracker" ],
          [ "PositionTracker", "class_signals_1_1_extras_1_1_utility_1_1_position_tracker.html", "class_signals_1_1_extras_1_1_utility_1_1_position_tracker" ],
          [ "RotationTracker", "class_signals_1_1_extras_1_1_utility_1_1_rotation_tracker.html", "class_signals_1_1_extras_1_1_utility_1_1_rotation_tracker" ]
        ] ]
      ] ],
      [ "ISignal", "interface_signals_1_1_i_signal.html", "interface_signals_1_1_i_signal" ],
      [ "Signal", "class_signals_1_1_signal.html", "class_signals_1_1_signal" ],
      [ "SignalEditor", "class_signals_1_1_signal_editor.html", "class_signals_1_1_signal_editor" ],
      [ "SignalListener", "class_signals_1_1_signal_listener.html", "class_signals_1_1_signal_listener" ],
      [ "ValueReference", "class_signals_1_1_value_reference.html", "class_signals_1_1_value_reference" ],
      [ "ValueReferenceComponent", "class_signals_1_1_value_reference_component.html", "class_signals_1_1_value_reference_component" ],
      [ "ValueReferenceDrawer", "class_signals_1_1_value_reference_drawer.html", "class_signals_1_1_value_reference_drawer" ]
    ] ]
];